name: Bug Report
description: Report a bug that needs to be fixed
title: "[BUGFIX] "
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the bug.
      placeholder: Describe the bug...
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: What should happen...
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
      placeholder: What actually happened...
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment (OS, version, etc.).
      placeholder: "OS: Windows 10, Version: 1.0.0"
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or logs related to the bug.
      placeholder: Any additional information...
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Select the severity level of this bug.
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
