name: Chore Task
description: Propose a minor maintenance or support task
title: "[CHORE] "
labels: ["chore"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the chore or maintenance task.
      placeholder: Describe the task...
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this task necessary?
      placeholder: Explain why...
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: List the specific tasks to be performed.
      placeholder: |
        - Task 1
        - Task 2
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or references.
      placeholder: Any additional information...
