name: Feature Request
description: Suggest a new feature or enhancement for the project
title: "[FEATURE] "
labels: ["enhancement", "feature"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the feature you are requesting.
      placeholder: Describe the feature in detail...
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this feature is needed. What problem does it solve?
      placeholder: Explain the problem and why this feature would help...
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: List the criteria that must be met for this feature to be considered complete.
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references related to this feature request.
      placeholder: Any additional information...
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority level for this feature request.
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
