[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    links2004/WebSockets@^2.7.0
    davylandman/Monocypher@^2.0.6
    ESP32Async/ESPAsyncWebServer
    ESP32Async/AsyncTCP
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DED25519_SHA512
    -DCORE_DEBUG_LEVEL=3
board_build.filesystem = littlefs
