name: Deploy Preview

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Preview
    runs-on: ubuntu-latest

    environment:
      name: Preview
      url: https://gitgost-qa.fly.dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only -c fly.qa.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
