name: Deploy Preview

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Preview
    runs-on: ubuntu-latest

    environment:
      name: Preview
      url: https://gitgost-qa.fly.dev

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Install flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> "$GITHUB_PATH"

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only -c fly.qa.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
